from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Transformation(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: Optional[str] = Field(
        default=None,
        alias="_id",
        description="Unique identifier of the transformation step.",
    )
    connection_id: str = Field(
        min_length=1,
        description="ID of the database connection.",
    )
    step_order: int = Field(
        ge=1,
        description="Transformation step order.",
    )
    name: str = Field(
        min_length=1,
        description="Name of the transformation step.",
    )
    sql_query: str = Field(
        min_length=1,
        description="SQL transformation query.",
    )
    output_view: str = Field(
        min_length=1,
        description=(
            "Name of the temporary output view generated by this step."
        ),
    )
    enabled: bool = Field(
        default=True,
        description="Whether the transformation step is active.",
    )